import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:tamenny_app/features/community/domain/entites/post_entity.dart';

final List<PostEntity> dummyPosts = [
  PostEntity(
      postId: '124131r32r',
      postText: 'This is a sample post text.',
      username: 'john_doe',
      userAvatarUrl: 'https://example.com/avatar.jpg',
      commentsCount: 10,
      likesCount: 100,
      sharesCount: 5,
      createdAt: Timestamp.now(),
      imageUrl: '',
      likedBy: ['user1']),
  PostEntity(
      likedBy: ['user1'],
      postId: '124131r32r',
      postText: 'This is a sample post text.',
      username: 'john_doe',
      userAvatarUrl: 'https://example.com/avatar.jpg',
      commentsCount: 10,
      likesCount: 100,
      sharesCount: 5,
      createdAt: Timestamp.now(),
      imageUrl: ''),
  PostEntity(
      postId: '124131r32r',
      postText: 'This is a sample post text.',
      username: 'john_doe',
      userAvatarUrl: 'https://example.com/avatar.jpg',
      commentsCount: 10,
      likesCount: 100,
      sharesCount: 5,
      createdAt: Timestamp.now(),
      imageUrl: '',
      likedBy: ['user1']),
  PostEntity(
      postId: '124131r32r',
      postText: 'This is a sample post text.',
      username: 'john_doe',
      userAvatarUrl: 'https://example.com/avatar.jpg',
      commentsCount: 10,
      likesCount: 100,
      sharesCount: 5,
      createdAt: Timestamp.now(),
      imageUrl: '',
      likedBy: ['user1']),
  PostEntity(
      postId: '124131r32r',
      postText: 'This is a sample post text.',
      username: 'john_doe',
      userAvatarUrl: 'https://example.com/avatar.jpg',
      commentsCount: 10,
      likesCount: 100,
      sharesCount: 5,
      createdAt: Timestamp.now(),
      imageUrl: '',
      likedBy: ['user1']),
  PostEntity(
      postId: '124131r32r',
      postText: 'This is a sample post text.',
      username: 'john_doe',
      userAvatarUrl: 'https://example.com/avatar.jpg',
      commentsCount: 10,
      likesCount: 100,
      sharesCount: 5,
      createdAt: Timestamp.now(),
      imageUrl: '',
      likedBy: ['user1'])
];
